# Generated by Django 4.2.23 on 2025-08-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockservice",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
