# Generated by Django 5.2.6 on 2025-09-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0002_alter_mockservice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockendpoint',
            name='default_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
