# Generated by Django 5.2.7 on 2025-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0002_mockrule_created_at_mockrule_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyauthconfig',
            name='failed_http_status',
            field=models.IntegerField(default=401),
        ),
        migrations.AddField(
            model_name='apikeyauthconfig',
            name='failed_response',
            field=models.JSONField(default={'error': 'Unauthorized'}),
        ),
        migrations.AddField(
            model_name='basicauthconfig',
            name='failed_http_status',
            field=models.IntegerField(default=401),
        ),
        migrations.AddField(
            model_name='basicauthconfig',
            name='failed_response',
            field=models.JSONField(default={'error': 'Unauthorized'}),
        ),
        migrations.AddField(
            model_name='jwtauthconfig',
            name='failed_http_status',
            field=models.IntegerField(default=401),
        ),
        migrations.AddField(
            model_name='jwtauthconfig',
            name='failed_response',
            field=models.JSONField(default={'error': 'Unauthorized'}),
        ),
    ]
