# Generated by Django 5.2.6 on 2025-09-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0003_mockendpoint_default_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockendpoint',
            name='default_http_status',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mockendpoint',
            name='default_response',
            field=models.JSONField(),
        ),
    ]
