# Generated by Django 5.2.7 on 2025-10-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0003_apikeyauthconfig_failed_http_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyauthconfig',
            name='failed_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='basicauthconfig',
            name='failed_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='jwtauthconfig',
            name='failed_response',
            field=models.JSONField(default=dict),
        ),
    ]
