# Generated by Django 5.2.7 on 2025-10-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0004_alter_apikeyauthconfig_failed_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyauthconfig',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicauthconfig',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jwtauthconfig',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockendpoint',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockrule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockservice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
