# Generated by Django 5.2.6 on 2025-09-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0004_mockendpoint_default_http_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockendpoint',
            name='require_auth',
        ),
    ]
