# Generated by Django 5.2.6 on 2025-09-08 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0005_remove_mockendpoint_require_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwtauthconfig',
            name='verify_key',
        ),
        migrations.AddField(
            model_name='jwtauthconfig',
            name='auth_header',
            field=models.CharField(default='Bearer'),
        ),
        migrations.AddField(
            model_name='jwtauthconfig',
            name='token',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
