# Generated by Django 5.2.6 on 2025-09-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0006_remove_jwtauthconfig_verify_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtauthconfig',
            name='token',
            field=models.TextField(),
        ),
    ]
