# Generated by Django 5.2.6 on 2025-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0007_alter_jwtauthconfig_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyauthconfig',
            name='header_name',
            field=models.CharField(default='API_KEY', max_length=100),
        ),
    ]
