# Generated by Django 5.2.6 on 2025-09-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0008_alter_apikeyauthconfig_header_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikeyauthconfig',
            old_name='header_name',
            new_name='key_name',
        ),
    ]
