# Generated by Django 5.2.6 on 2025-09-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0009_rename_header_name_apikeyauthconfig_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyauthconfig',
            name='add_to',
            field=models.CharField(choices=[('header', 'Header'), ('query_params', 'Query Params')], default='header', max_length=50),
            preserve_default=False,
        ),
    ]
