# Generated by Django 5.2.6 on 2025-09-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0010_apikeyauthconfig_add_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockrule',
            name='method',
            field=models.CharField(choices=[('PAYLOAD', 'PAYLOAD'), ('QUERY_PARAMS', 'QUERY PARAMS')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
