# Generated by Django 5.2.6 on 2025-09-09 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0011_mockrule_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockrule',
            old_name='method',
            new_name='request_source',
        ),
        migrations.AddField(
            model_name='mockrule',
            name='data_format',
            field=models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
