# Generated by Django 5.2.6 on 2025-09-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0012_rename_method_mockrule_request_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockendpoint',
            name='hit_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
